Fix missing colon in mkdocs configuration file
Error: MkDocs encountered an error parsing the configuration file: mapping values are not allowed here\nin "/home/runner/work/8311/8311/mkdocs.yml", line 20, column 15